package org.javalabs.decl.compile;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.tools.FileObject;
import javax.tools.ForwardingJavaFileManager;
import javax.tools.JavaFileManager;
import javax.tools.JavaFileObject;
import javax.tools.JavaFileObject.Kind;

/**
 *
 * @author schan280
 */
public class InMemoryFileManager extends ForwardingJavaFileManager<JavaFileManager> {
    
    // The compiled results as Map that contains class name as key and class binary as value.
    private final Map<String, JavaCompiledClass> compiledClasses = new HashMap<>();

    InMemoryFileManager(JavaFileManager fileManager) {
        super(fileManager);
    }

    public Map<String, JavaCompiledClass> compiledClasses() {
        return this.compiledClasses;
    }

    @Override
    public void flush() throws IOException {
    }
    
    public JavaCompiledClass getCompileClass(String className) {
        return this.compiledClasses.get(className);
    }

    @Override
    public void close() throws IOException {
        // Post compilation, and after the generated class bytes have been written in the JavaCompiledClass object,
        // The file manager will be closed.
        this.compiledClasses.clear();
    }

    @Override
    public JavaFileObject getJavaFileForOutput(JavaFileManager.Location location
            , String className
            , Kind kind
            , FileObject sibling) throws IOException {
        
        // This method will be invoked by the JavaCompiler, post compiling the file.
        // The location is CLASS_OUTPUT
        // The className is the fully qualified class name (package name + java file name)
        // The kind will be CLASS, since the class byte has already been generated by the compiler.
        // sibling is the JavaSource object that was created initially. It has the raw file content.
        // 
        // The call hierarchy:
        // JavacTaskImpl.call -> .... -> .... -> JavaCompiler.compile -> JavaCompiler.generate -> JavaCompiler.genCode -> ClassWriter.writeClass
        //
        if (kind == Kind.CLASS) {
            JavaCompiledClass jcc = new JavaCompiledClass(className);
            compiledClasses.put(className, jcc);
            
            return jcc;
        }
        else {
            return super.getJavaFileForOutput(location, className, kind, sibling);
        }
    }

    public JavaFileObject make(String javaFile, String content) {
        return new JavaSource(javaFile, content);
    }
}
