#!/bin/sh

set CLASSPATH=ecm-container-0.0.1-SNAPSHOT.jar
set CLASSPATH=$CLASSPATH:ecm-util-0.0.1-SNAPSHOT.jar
set CLASSPATH=$CLASSPATH:ecm-vertx-config-0.0.1-SNAPSHOT.jar
set CLASSPATH=$CLASSPATH:jackson-annotations-2.13.4.jar
set CLASSPATH=$CLASSPATH:jackson-core-2.16.1.jar
set CLASSPATH=$CLASSPATH:jackson-databind-2.13.4.2.jar
set CLASSPATH=$CLASSPATH:jackson-dataformat-yaml-2.13.4.jar
set CLASSPATH=$CLASSPATH:netty-buffer-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-codec-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-codec-dns-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-codec-http-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-codec-http2-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-codec-socks-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-common-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-handler-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-handler-proxy-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-resolver-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-resolver-dns-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-transport-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:netty-transport-native-unix-common-4.1.107.Final.jar
set CLASSPATH=$CLASSPATH:slf4j-api-1.7.27.jar
set CLASSPATH=$CLASSPATH:slf4j-simple-1.7.27.jar
set CLASSPATH=$CLASSPATH:snakeyaml-1.31.jar
set CLASSPATH=$CLASSPATH:vertx-auth-common-4.5.4.jar
set CLASSPATH=$CLASSPATH:vertx-bridge-common-4.5.4.jar
set CLASSPATH=$CLASSPATH:vertx-core-4.5.4.jar
set CLASSPATH=$CLASSPATH:vertx-web-4.5.4.jar
set CLASSPATH=$CLASSPATH:vertx-web-common-4.5.4.jar

java -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9791 -jar target/ecm-swagger-doc-0.0.1-SNAPSHOT.jar